image: php:7.3.20

test:
  script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-5.7.27.phar
    - chmod +x /usr/local/bin/phpunit
    - pecl install xdebug-2.9.7
    - docker-php-ext-enable xdebug
    - echo "date.timezone = Europe/Warsaw" > /usr/local/etc/php/php.ini
    - cd tests/
    - phpunit --coverage-html /builds/moiz.ahmed/training_project/tests/coverage/
  artifacts:
    paths:
      - /builds/moiz.ahmed/training_project/tests/coverage/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv /builds/moiz.ahmed/training_project/tests/coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
